name: Daily Update

on:
  schedule:
    - cron: "20 * * * *"
  
defaults:
    run:
        shell: bash 
    
jobs:
    submoduleupdate:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         token: ${{ secrets.CI_TOKEN }}
         submodules: true

      - name: Update submodules
        run: |
          git submodule update --remote --recursive

      - name: Commit changes
        run: |
          git config --global user.name 'GitHubActionRunner'
          git config --global user.email 'actions@github.com'
          git add --all
          git commit -m "Submodule update"
          git push
          
    codelinecount:
     runs-on: ubuntu-latest
     name: Code line counting
     steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Count the LoC
        id: scc
        uses: Adapt-API/scc-docker-action@master
        with:
          args: ${{ env.workspace }} -i html,css,js
      - name: Output
        run: |
          echo
          echo -n "${{ steps.scc.outputs.scc }}"

    pageshourly:
     runs-on: ubuntu-latest
     steps:
      - name: Deployment
        id: deployment
        uses: actions/deploy-pages@v3 # or the latest "vX.X.X" version tag for this action
