#Updates submodules, counts code and commits it triggering a web rebuild

name: WebsiteUpdate

on:
  schedule:
    - cron: "15 0,6,12,18 * * *"
  workflow_dispatch:
  push:
 
jobs:
  updatesubmodule_eg:
    name: Submodule Update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: "pagedeployment"
        submodules: true
    - name: Update submodules
      shell: bash
      run: |
        git config --global pull.rebase true
        git config --global user.email "actions@github.com"
        git config --global user.name "Website Content Update"
        git submodule update --recursive --remote
        git commit -am "Submodule update" --allow-empty
        git push
    - name: Push to GH Pages branch
  codelinecount:
    name: Code Counting Web only
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: false
    - name: Count code
      id: scc
      uses: Adapt-API/scc-docker-action@master
      with:
        args: ${{ env.workspace }} -i html,css,js,ts
    - name: Output
      shell: bash
      run: |
        echo
        echo -n "${{ steps.scc.outputs.scc }}"
    
